const projects = [
  {
    id: 'project3',
    title: 'Full-Stack E-Commerce Platform',
    img: '/project3/project3.webp',
    link: '/projects/project3',
    date: '2023',
    liveLink: 'https://www.github.com/rimondutta/',
    company: 'Company 2',
    primary: '#2D2D2D',
    accentColor: '#FCFBF7',
    secondary: '#F2EEE7',
    fillColor: '#F2F3F4',
    menuColor: 'gold',
    menuFontColor: '#2D2D2D',
    fluidColor: '#0028FF',
    images: [
      {
        src: '/project3/video.mp4',
        tag: 'video',
        isRight: false,
      },
      {
        src: '/project3/7.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project3/6.webp',
        tag: 'small',
        isRight: true,
      },
      {
        src: '/project3/video2.mp4',
        tag: 'video',
        isRight: false,
      },
      {
        src: '/project3/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project3/5.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project3/8.webp',
        tag: 'small',
        isRight: true,
      },
      {
        src: '/project3/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project3/3.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'Tech Stack: React.js • Node.js • Express.js • MongoDB • Redux • Tailwind CSS • Stripe API • Cloudinary • JWT Auth',
      'UrbanKart is a modern, responsive full-stack e-commerce web application that allows users to browse products, add items to their cart, and complete secure checkouts using Stripe. Admins can manage products, orders, and inventory through a dedicated dashboard. The project focuses on clean design, performance optimization, and end-to-end functionality.',
      'Key Features',
      'User:',
      'Account registration & secure login (JWT-based)',
      'Product browsing with filters (category, price, rating)',
      'Add to cart, update quantity, remove item',
      'Checkout process with Stripe payment integration',
      'View order history & track order status',
      'Admin:',
      'Admin dashboard with analytics',
      'Create, edit, or delete products',
      'Manage orders (approve, reject, shipped)',
      'Upload product images via Cloudinary',
      'View registered users and activity',
    ],
  },
  {
    id: 'project4',
    title: 'Hotel Booking System',
    img: '/project4/project4.webp',
    link: '/projects/project4',
    date: '2024',
    company: 'Company 1',
    liveLink: 'https://www.github.com/rimondutta/',
    primary: '#263745',
    accentColor: '#f0f4f1',
    secondary: '#F3F5F7',
    fillColor: '#E0DFFC',
    menuColor: '#5C58EB',
    menuFontColor: '#f0f4f1',
    fluidColor: '#A3A714',
    images: [
      {
        src: '/project4/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/2.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/3.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/4.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/5.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/6.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/7.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/8.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/9.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/10.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/11.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'Tech Stack: MERN Stack + Date Picker + Email API',
      'A hotel and room reservation system with real-time availability checks, booking calendar, and email confirmation. Admins can manage room inventory and view booking status.',
      'Features:',
      'Room availability & filtering',
      'Booking confirmation via email',
      'Calendar-based reservation system',
      'Admin room & booking management',
      'Guest feedback section',
    ],
  },
  {
    id: 'project5',
    title: 'Invoice Generator',
    img: '/project5/project5.webp',
    link: '/projects/project5',
    date: '2024',
    company: 'Project 5',
    liveLink: 'https://www.github.com/rimondutta/',
    primary: '#000000',
    accentColor: '#f0f4f1',
    secondary: '#FAFAFA',
    fillColor: '#f2f2f2',
    menuColor: '#FFD54F',
    menuFontColor: '#000000',
    fluidColor: '#002AB0',
    images: [
      {
        src: '/project5/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/3.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project5/4.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project5/5.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/6.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/7.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/8.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/9.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project5/10.webp',
        tag: 'medium',
        isRight: false,
      },
    ],
    desc: [
      'Tech Stack: MERN Stack + PDFKit + JWT Auth',
      'An invoice generation and client management app for freelancers and small businesses. Users can create, download, and send branded PDF invoices.',
      'Features:',
      'Client & project management',
      'Custom invoice builder',
      'PDF export & email delivery',
      'Currency & tax calculator',
      'Responsive mobile-first design',
    ],
  },
  {
    id: 'project1',
    title: 'E-Commerce Store',
    img: '/project1/project1.webp',
    link: '/projects/project1',
    date: '2024',
    company: 'Company 4',
    liveLink: 'https://www.github.com/rimondutta/',
    primary: '#000000',
    accentColor: '#f0f4f1',
    secondary: '#F9F9F9',
    fillColor: '#ebfaf8',
    menuColor: '#00a8c1',
    menuFontColor: '#f0f4f1',
    fluidColor: '#FF573E',
    images: [
      {
        src: '/project1/video.mp4',
        tag: 'video',
        isRight: false,
      },
      {
        src: '/project1/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/2.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project1/7.webp',
        tag: 'small',
        isRight: true,
      },
      {
        src: '/project1/5.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/6.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/8.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/3.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project1/4.webp',
        tag: 'small',
        isRight: true,
      },
    ],
    desc: [
      'Tech Stack: MERN Stack + Stripe API + Cloudinary',
      'A fully functional e-commerce platform allowing users to browse products, add items to cart, and securely check out. Admins can manage products, categories, and view sales analytics via a dedicated dashboard.',
      'Features:',
      'Product listing with search & filter',
      'User signup/login and order history',
      'Admin product & order management',
      'Payment integration with Stripe',
      'Image upload via Cloudinary',
    ],
  },
  {
    id: 'project2',
    title: 'Student Task Manager',
    img: '/project2/project2.webp',
    link: '/projects/project2',
    date: '2024',
    company: 'Company 3',
    liveLink: 'https://www.github.com/rimondutta/',
    primary: '#0e0063',
    accentColor: '#f0f4f1',
    secondary: '#fbfbfc',
    fillColor: '#e1e1f9',
    menuColor: '#170053',
    menuFontColor: '#f0f4f1',
    fluidColor: '#E8FFC8',
    images: [
      {
        src: '/project2/video.mp4',
        tag: 'video',
        isRight: true,
      },
      {
        src: '/project2/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project2/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project2/3.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'Tech Stack: MERN (MongoDB, Express.js, React.js, Node.js)',
      'A task management web app designed for students to track assignments, deadlines, and personal goals. Features include user registration, task creation, priority labels, and a dashboard view of upcoming tasks. Data is stored in MongoDB with full CRUD capabilities.',
      'Features:',
      'Task categorization by subject',
      'Deadline calendar view',
      'JWT-based authentication',
      'Responsive UI with Tailwind CSS',
    ],
  },
];
export default projects;
